# Generated by Django 5.2.1 on 2025-05-09 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('paga', models.BooleanField(default=True)),
                ('identificacion', models.IntegerField()),
                ('codigo_reserva', models.CharField(blank=True, max_length=20, unique=True)),
                ('fechaInicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Reservar habitacion'), (2, 'Reservar salon')], default=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('personas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('especificacion', models.TextField(max_length=200)),
                ('numero', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
