# Generated by Django 5.2.1 on 2025-05-09 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reserva_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='servicio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.servicio'),
        ),
    ]
