# Generated by Django 5.2.1 on 2025-05-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_reserva_codigo_reserva_alter_reserva_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(default='TEMP', max_length=20, unique=True),
        ),
    ]
