# Generated by Django 5.2.1 on 2025-05-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_reserva_codigo_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
