# Generated by Django 5.2.1 on 2025-05-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_reserva_codigo_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fechaFin',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(blank=True, default='RES', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='paga',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'HABITACION'), (2, 'SALON')], default=1),
        ),
    ]
