# Generated by Django 5.2.1 on 2025-05-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_reserva_fechafin_alter_reserva_codigo_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fechaFin',
            field=models.DateField(default='00/00/00'),
        ),
    ]
