# Generated by Django 5.2.1 on 2025-05-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_reserva_fechafin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fechaFin',
            field=models.DateField(),
        ),
    ]
