# Generated by Django 5.2.1 on 2025-05-11 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_reserva_fechafin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='identificacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3)]),
        ),
    ]
