# Generated by Django 5.2.1 on 2025-08-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_reserva_codigo_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
